[package]
name = "Supa"
version = "0.1.0"
description = "Supa"
authors = ["Dmitry Kury"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "supa_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.1.1", features = [] }

[dependencies]
tauri = { version = " 2.4.1", features = ["devtools"] }
tauri-plugin-shell = " 2.2.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-fs = { version = " 2.2.1", features = ["watch"] }
tauri-plugin-dialog = " 2.2.1"
tauri-plugin-process = "2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"

